/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionsBillingUsageMinutesUsedBreakdown model module.
 * @module model/ActionsBillingUsageMinutesUsedBreakdown
 * @version 0.0.5
 */
class ActionsBillingUsageMinutesUsedBreakdown {
    /**
     * Constructs a new <code>ActionsBillingUsageMinutesUsedBreakdown</code>.
     * @alias module:model/ActionsBillingUsageMinutesUsedBreakdown
     */
    constructor() { 
        
        ActionsBillingUsageMinutesUsedBreakdown.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionsBillingUsageMinutesUsedBreakdown</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionsBillingUsageMinutesUsedBreakdown} obj Optional instance to populate.
     * @return {module:model/ActionsBillingUsageMinutesUsedBreakdown} The populated <code>ActionsBillingUsageMinutesUsedBreakdown</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionsBillingUsageMinutesUsedBreakdown();

            if (data.hasOwnProperty('MACOS')) {
                obj['MACOS'] = ApiClient.convertToType(data['MACOS'], 'Number');
            }
            if (data.hasOwnProperty('UBUNTU')) {
                obj['UBUNTU'] = ApiClient.convertToType(data['UBUNTU'], 'Number');
            }
            if (data.hasOwnProperty('WINDOWS')) {
                obj['WINDOWS'] = ApiClient.convertToType(data['WINDOWS'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Total minutes used on macOS runner machines.
 * @member {Number} MACOS
 */
ActionsBillingUsageMinutesUsedBreakdown.prototype['MACOS'] = undefined;

/**
 * Total minutes used on Ubuntu runner machines.
 * @member {Number} UBUNTU
 */
ActionsBillingUsageMinutesUsedBreakdown.prototype['UBUNTU'] = undefined;

/**
 * Total minutes used on Windows runner machines.
 * @member {Number} WINDOWS
 */
ActionsBillingUsageMinutesUsedBreakdown.prototype['WINDOWS'] = undefined;






export default ActionsBillingUsageMinutesUsedBreakdown;

