/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiOverviewSshKeyFingerprints from './ApiOverviewSshKeyFingerprints';

/**
 * The ApiOverview model module.
 * @module model/ApiOverview
 * @version 0.0.5
 */
class ApiOverview {
    /**
     * Constructs a new <code>ApiOverview</code>.
     * Api Overview
     * @alias module:model/ApiOverview
     * @param verifiablePasswordAuthentication {Boolean} 
     */
    constructor(verifiablePasswordAuthentication) { 
        
        ApiOverview.initialize(this, verifiablePasswordAuthentication);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, verifiablePasswordAuthentication) { 
        obj['verifiable_password_authentication'] = verifiablePasswordAuthentication;
    }

    /**
     * Constructs a <code>ApiOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiOverview} obj Optional instance to populate.
     * @return {module:model/ApiOverview} The populated <code>ApiOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiOverview();

            if (data.hasOwnProperty('api')) {
                obj['api'] = ApiClient.convertToType(data['api'], ['String']);
            }
            if (data.hasOwnProperty('git')) {
                obj['git'] = ApiClient.convertToType(data['git'], ['String']);
            }
            if (data.hasOwnProperty('github_services_sha')) {
                obj['github_services_sha'] = ApiClient.convertToType(data['github_services_sha'], 'String');
            }
            if (data.hasOwnProperty('hooks')) {
                obj['hooks'] = ApiClient.convertToType(data['hooks'], ['String']);
            }
            if (data.hasOwnProperty('importer')) {
                obj['importer'] = ApiClient.convertToType(data['importer'], ['String']);
            }
            if (data.hasOwnProperty('installed_version')) {
                obj['installed_version'] = ApiClient.convertToType(data['installed_version'], 'String');
            }
            if (data.hasOwnProperty('pages')) {
                obj['pages'] = ApiClient.convertToType(data['pages'], ['String']);
            }
            if (data.hasOwnProperty('ssh_key_fingerprints')) {
                obj['ssh_key_fingerprints'] = ApiOverviewSshKeyFingerprints.constructFromObject(data['ssh_key_fingerprints']);
            }
            if (data.hasOwnProperty('verifiable_password_authentication')) {
                obj['verifiable_password_authentication'] = ApiClient.convertToType(data['verifiable_password_authentication'], 'Boolean');
            }
            if (data.hasOwnProperty('web')) {
                obj['web'] = ApiClient.convertToType(data['web'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} api
 */
ApiOverview.prototype['api'] = undefined;

/**
 * @member {Array.<String>} git
 */
ApiOverview.prototype['git'] = undefined;

/**
 * @member {String} github_services_sha
 */
ApiOverview.prototype['github_services_sha'] = undefined;

/**
 * @member {Array.<String>} hooks
 */
ApiOverview.prototype['hooks'] = undefined;

/**
 * @member {Array.<String>} importer
 */
ApiOverview.prototype['importer'] = undefined;

/**
 * @member {String} installed_version
 */
ApiOverview.prototype['installed_version'] = undefined;

/**
 * @member {Array.<String>} pages
 */
ApiOverview.prototype['pages'] = undefined;

/**
 * @member {module:model/ApiOverviewSshKeyFingerprints} ssh_key_fingerprints
 */
ApiOverview.prototype['ssh_key_fingerprints'] = undefined;

/**
 * @member {Boolean} verifiable_password_authentication
 */
ApiOverview.prototype['verifiable_password_authentication'] = undefined;

/**
 * @member {Array.<String>} web
 */
ApiOverview.prototype['web'] = undefined;






export default ApiOverview;

