/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationGrantApp model module.
 * @module model/ApplicationGrantApp
 * @version 0.0.5
 */
class ApplicationGrantApp {
    /**
     * Constructs a new <code>ApplicationGrantApp</code>.
     * @alias module:model/ApplicationGrantApp
     * @param clientId {String} 
     * @param name {String} 
     * @param url {String} 
     */
    constructor(clientId, name, url) { 
        
        ApplicationGrantApp.initialize(this, clientId, name, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, clientId, name, url) { 
        obj['client_id'] = clientId;
        obj['name'] = name;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>ApplicationGrantApp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationGrantApp} obj Optional instance to populate.
     * @return {module:model/ApplicationGrantApp} The populated <code>ApplicationGrantApp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationGrantApp();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} client_id
 */
ApplicationGrantApp.prototype['client_id'] = undefined;

/**
 * @member {String} name
 */
ApplicationGrantApp.prototype['name'] = undefined;

/**
 * @member {String} url
 */
ApplicationGrantApp.prototype['url'] = undefined;






export default ApplicationGrantApp;

