/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyType from './AnyType';
import BaseGistFiles from './BaseGistFiles';
import SimpleUser from './SimpleUser';

/**
 * The BaseGist model module.
 * @module model/BaseGist
 * @version 0.0.5
 */
class BaseGist {
    /**
     * Constructs a new <code>BaseGist</code>.
     * Base Gist
     * @alias module:model/BaseGist
     * @param comments {Number} 
     * @param commentsUrl {String} 
     * @param commitsUrl {String} 
     * @param createdAt {Date} 
     * @param description {String} 
     * @param files {Object.<String, module:model/BaseGistFiles>} 
     * @param forksUrl {String} 
     * @param gitPullUrl {String} 
     * @param gitPushUrl {String} 
     * @param htmlUrl {String} 
     * @param id {String} 
     * @param nodeId {String} 
     * @param _public {Boolean} 
     * @param updatedAt {Date} 
     * @param url {String} 
     * @param user {module:model/SimpleUser} 
     */
    constructor(comments, commentsUrl, commitsUrl, createdAt, description, files, forksUrl, gitPullUrl, gitPushUrl, htmlUrl, id, nodeId, _public, updatedAt, url, user) { 
        
        BaseGist.initialize(this, comments, commentsUrl, commitsUrl, createdAt, description, files, forksUrl, gitPullUrl, gitPushUrl, htmlUrl, id, nodeId, _public, updatedAt, url, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, comments, commentsUrl, commitsUrl, createdAt, description, files, forksUrl, gitPullUrl, gitPushUrl, htmlUrl, id, nodeId, _public, updatedAt, url, user) { 
        obj['comments'] = comments;
        obj['comments_url'] = commentsUrl;
        obj['commits_url'] = commitsUrl;
        obj['created_at'] = createdAt;
        obj['description'] = description;
        obj['files'] = files;
        obj['forks_url'] = forksUrl;
        obj['git_pull_url'] = gitPullUrl;
        obj['git_push_url'] = gitPushUrl;
        obj['html_url'] = htmlUrl;
        obj['id'] = id;
        obj['node_id'] = nodeId;
        obj['public'] = _public;
        obj['updated_at'] = updatedAt;
        obj['url'] = url;
        obj['user'] = user;
    }

    /**
     * Constructs a <code>BaseGist</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseGist} obj Optional instance to populate.
     * @return {module:model/BaseGist} The populated <code>BaseGist</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseGist();

            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'Number');
            }
            if (data.hasOwnProperty('comments_url')) {
                obj['comments_url'] = ApiClient.convertToType(data['comments_url'], 'String');
            }
            if (data.hasOwnProperty('commits_url')) {
                obj['commits_url'] = ApiClient.convertToType(data['commits_url'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], {'String': BaseGistFiles});
            }
            if (data.hasOwnProperty('forks')) {
                obj['forks'] = ApiClient.convertToType(data['forks'], [AnyType]);
            }
            if (data.hasOwnProperty('forks_url')) {
                obj['forks_url'] = ApiClient.convertToType(data['forks_url'], 'String');
            }
            if (data.hasOwnProperty('git_pull_url')) {
                obj['git_pull_url'] = ApiClient.convertToType(data['git_pull_url'], 'String');
            }
            if (data.hasOwnProperty('git_push_url')) {
                obj['git_push_url'] = ApiClient.convertToType(data['git_push_url'], 'String');
            }
            if (data.hasOwnProperty('history')) {
                obj['history'] = ApiClient.convertToType(data['history'], [AnyType]);
            }
            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], SimpleUser);
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
            }
            if (data.hasOwnProperty('truncated')) {
                obj['truncated'] = ApiClient.convertToType(data['truncated'], 'Boolean');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], SimpleUser);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} comments
 */
BaseGist.prototype['comments'] = undefined;

/**
 * @member {String} comments_url
 */
BaseGist.prototype['comments_url'] = undefined;

/**
 * @member {String} commits_url
 */
BaseGist.prototype['commits_url'] = undefined;

/**
 * @member {Date} created_at
 */
BaseGist.prototype['created_at'] = undefined;

/**
 * @member {String} description
 */
BaseGist.prototype['description'] = undefined;

/**
 * @member {Object.<String, module:model/BaseGistFiles>} files
 */
BaseGist.prototype['files'] = undefined;

/**
 * @member {Array.<module:model/AnyType>} forks
 */
BaseGist.prototype['forks'] = undefined;

/**
 * @member {String} forks_url
 */
BaseGist.prototype['forks_url'] = undefined;

/**
 * @member {String} git_pull_url
 */
BaseGist.prototype['git_pull_url'] = undefined;

/**
 * @member {String} git_push_url
 */
BaseGist.prototype['git_push_url'] = undefined;

/**
 * @member {Array.<module:model/AnyType>} history
 */
BaseGist.prototype['history'] = undefined;

/**
 * @member {String} html_url
 */
BaseGist.prototype['html_url'] = undefined;

/**
 * @member {String} id
 */
BaseGist.prototype['id'] = undefined;

/**
 * @member {String} node_id
 */
BaseGist.prototype['node_id'] = undefined;

/**
 * @member {module:model/SimpleUser} owner
 */
BaseGist.prototype['owner'] = undefined;

/**
 * @member {Boolean} public
 */
BaseGist.prototype['public'] = undefined;

/**
 * @member {Boolean} truncated
 */
BaseGist.prototype['truncated'] = undefined;

/**
 * @member {Date} updated_at
 */
BaseGist.prototype['updated_at'] = undefined;

/**
 * @member {String} url
 */
BaseGist.prototype['url'] = undefined;

/**
 * @member {module:model/SimpleUser} user
 */
BaseGist.prototype['user'] = undefined;






export default BaseGist;

