/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BaseGistFiles model module.
 * @module model/BaseGistFiles
 * @version 0.0.5
 */
class BaseGistFiles {
    /**
     * Constructs a new <code>BaseGistFiles</code>.
     * @alias module:model/BaseGistFiles
     */
    constructor() { 
        
        BaseGistFiles.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BaseGistFiles</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseGistFiles} obj Optional instance to populate.
     * @return {module:model/BaseGistFiles} The populated <code>BaseGistFiles</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseGistFiles();

            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('raw_url')) {
                obj['raw_url'] = ApiClient.convertToType(data['raw_url'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} filename
 */
BaseGistFiles.prototype['filename'] = undefined;

/**
 * @member {String} language
 */
BaseGistFiles.prototype['language'] = undefined;

/**
 * @member {String} raw_url
 */
BaseGistFiles.prototype['raw_url'] = undefined;

/**
 * @member {Number} size
 */
BaseGistFiles.prototype['size'] = undefined;

/**
 * @member {String} type
 */
BaseGistFiles.prototype['type'] = undefined;






export default BaseGistFiles;

