/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BasicError model module.
 * @module model/BasicError
 * @version 0.0.5
 */
class BasicError {
    /**
     * Constructs a new <code>BasicError</code>.
     * Basic Error
     * @alias module:model/BasicError
     */
    constructor() { 
        
        BasicError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BasicError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BasicError} obj Optional instance to populate.
     * @return {module:model/BasicError} The populated <code>BasicError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BasicError();

            if (data.hasOwnProperty('documentation_url')) {
                obj['documentation_url'] = ApiClient.convertToType(data['documentation_url'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} documentation_url
 */
BasicError.prototype['documentation_url'] = undefined;

/**
 * @member {String} message
 */
BasicError.prototype['message'] = undefined;






export default BasicError;

