/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BranchProtectionRequiredStatusChecks model module.
 * @module model/BranchProtectionRequiredStatusChecks
 * @version 0.0.5
 */
class BranchProtectionRequiredStatusChecks {
    /**
     * Constructs a new <code>BranchProtectionRequiredStatusChecks</code>.
     * @alias module:model/BranchProtectionRequiredStatusChecks
     * @param contexts {Array.<String>} 
     * @param enforcementLevel {String} 
     */
    constructor(contexts, enforcementLevel) { 
        
        BranchProtectionRequiredStatusChecks.initialize(this, contexts, enforcementLevel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contexts, enforcementLevel) { 
        obj['contexts'] = contexts;
        obj['enforcement_level'] = enforcementLevel;
    }

    /**
     * Constructs a <code>BranchProtectionRequiredStatusChecks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BranchProtectionRequiredStatusChecks} obj Optional instance to populate.
     * @return {module:model/BranchProtectionRequiredStatusChecks} The populated <code>BranchProtectionRequiredStatusChecks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BranchProtectionRequiredStatusChecks();

            if (data.hasOwnProperty('contexts')) {
                obj['contexts'] = ApiClient.convertToType(data['contexts'], ['String']);
            }
            if (data.hasOwnProperty('contexts_url')) {
                obj['contexts_url'] = ApiClient.convertToType(data['contexts_url'], 'String');
            }
            if (data.hasOwnProperty('enforcement_level')) {
                obj['enforcement_level'] = ApiClient.convertToType(data['enforcement_level'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} contexts
 */
BranchProtectionRequiredStatusChecks.prototype['contexts'] = undefined;

/**
 * @member {String} contexts_url
 */
BranchProtectionRequiredStatusChecks.prototype['contexts_url'] = undefined;

/**
 * @member {String} enforcement_level
 */
BranchProtectionRequiredStatusChecks.prototype['enforcement_level'] = undefined;

/**
 * @member {String} url
 */
BranchProtectionRequiredStatusChecks.prototype['url'] = undefined;






export default BranchProtectionRequiredStatusChecks;

