/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BranchProtectionAllowDeletions from './BranchProtectionAllowDeletions';
import BranchProtectionRequiredStatusChecks from './BranchProtectionRequiredStatusChecks';
import BranchRestrictionPolicy from './BranchRestrictionPolicy';
import ProtectedBranchAdminEnforced from './ProtectedBranchAdminEnforced';
import ProtectedBranchPullRequestReview from './ProtectedBranchPullRequestReview';

/**
 * The BranchProtection model module.
 * @module model/BranchProtection
 * @version 0.0.5
 */
class BranchProtection {
    /**
     * Constructs a new <code>BranchProtection</code>.
     * Branch Protection
     * @alias module:model/BranchProtection
     * @param enabled {Boolean} 
     * @param requiredStatusChecks {module:model/BranchProtectionRequiredStatusChecks} 
     */
    constructor(enabled, requiredStatusChecks) { 
        
        BranchProtection.initialize(this, enabled, requiredStatusChecks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled, requiredStatusChecks) { 
        obj['enabled'] = enabled;
        obj['required_status_checks'] = requiredStatusChecks;
    }

    /**
     * Constructs a <code>BranchProtection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BranchProtection} obj Optional instance to populate.
     * @return {module:model/BranchProtection} The populated <code>BranchProtection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BranchProtection();

            if (data.hasOwnProperty('allow_deletions')) {
                obj['allow_deletions'] = BranchProtectionAllowDeletions.constructFromObject(data['allow_deletions']);
            }
            if (data.hasOwnProperty('allow_force_pushes')) {
                obj['allow_force_pushes'] = BranchProtectionAllowDeletions.constructFromObject(data['allow_force_pushes']);
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('enforce_admins')) {
                obj['enforce_admins'] = ProtectedBranchAdminEnforced.constructFromObject(data['enforce_admins']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('protection_url')) {
                obj['protection_url'] = ApiClient.convertToType(data['protection_url'], 'String');
            }
            if (data.hasOwnProperty('required_linear_history')) {
                obj['required_linear_history'] = BranchProtectionAllowDeletions.constructFromObject(data['required_linear_history']);
            }
            if (data.hasOwnProperty('required_pull_request_reviews')) {
                obj['required_pull_request_reviews'] = ProtectedBranchPullRequestReview.constructFromObject(data['required_pull_request_reviews']);
            }
            if (data.hasOwnProperty('required_status_checks')) {
                obj['required_status_checks'] = BranchProtectionRequiredStatusChecks.constructFromObject(data['required_status_checks']);
            }
            if (data.hasOwnProperty('restrictions')) {
                obj['restrictions'] = BranchRestrictionPolicy.constructFromObject(data['restrictions']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BranchProtectionAllowDeletions} allow_deletions
 */
BranchProtection.prototype['allow_deletions'] = undefined;

/**
 * @member {module:model/BranchProtectionAllowDeletions} allow_force_pushes
 */
BranchProtection.prototype['allow_force_pushes'] = undefined;

/**
 * @member {Boolean} enabled
 */
BranchProtection.prototype['enabled'] = undefined;

/**
 * @member {module:model/ProtectedBranchAdminEnforced} enforce_admins
 */
BranchProtection.prototype['enforce_admins'] = undefined;

/**
 * @member {String} name
 */
BranchProtection.prototype['name'] = undefined;

/**
 * @member {String} protection_url
 */
BranchProtection.prototype['protection_url'] = undefined;

/**
 * @member {module:model/BranchProtectionAllowDeletions} required_linear_history
 */
BranchProtection.prototype['required_linear_history'] = undefined;

/**
 * @member {module:model/ProtectedBranchPullRequestReview} required_pull_request_reviews
 */
BranchProtection.prototype['required_pull_request_reviews'] = undefined;

/**
 * @member {module:model/BranchProtectionRequiredStatusChecks} required_status_checks
 */
BranchProtection.prototype['required_status_checks'] = undefined;

/**
 * @member {module:model/BranchRestrictionPolicy} restrictions
 */
BranchProtection.prototype['restrictions'] = undefined;

/**
 * @member {String} url
 */
BranchProtection.prototype['url'] = undefined;






export default BranchProtection;

