/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckRunCheckSuite model module.
 * @module model/CheckRunCheckSuite
 * @version 0.0.5
 */
class CheckRunCheckSuite {
    /**
     * Constructs a new <code>CheckRunCheckSuite</code>.
     * @alias module:model/CheckRunCheckSuite
     * @param id {Number} 
     */
    constructor(id) { 
        
        CheckRunCheckSuite.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>CheckRunCheckSuite</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckRunCheckSuite} obj Optional instance to populate.
     * @return {module:model/CheckRunCheckSuite} The populated <code>CheckRunCheckSuite</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckRunCheckSuite();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
CheckRunCheckSuite.prototype['id'] = undefined;






export default CheckRunCheckSuite;

