/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckSuitePreferencePreferencesAutoTriggerChecks model module.
 * @module model/CheckSuitePreferencePreferencesAutoTriggerChecks
 * @version 0.0.5
 */
class CheckSuitePreferencePreferencesAutoTriggerChecks {
    /**
     * Constructs a new <code>CheckSuitePreferencePreferencesAutoTriggerChecks</code>.
     * @alias module:model/CheckSuitePreferencePreferencesAutoTriggerChecks
     * @param appId {Number} 
     * @param setting {Boolean} 
     */
    constructor(appId, setting) { 
        
        CheckSuitePreferencePreferencesAutoTriggerChecks.initialize(this, appId, setting);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appId, setting) { 
        obj['app_id'] = appId;
        obj['setting'] = setting;
    }

    /**
     * Constructs a <code>CheckSuitePreferencePreferencesAutoTriggerChecks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckSuitePreferencePreferencesAutoTriggerChecks} obj Optional instance to populate.
     * @return {module:model/CheckSuitePreferencePreferencesAutoTriggerChecks} The populated <code>CheckSuitePreferencePreferencesAutoTriggerChecks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckSuitePreferencePreferencesAutoTriggerChecks();

            if (data.hasOwnProperty('app_id')) {
                obj['app_id'] = ApiClient.convertToType(data['app_id'], 'Number');
            }
            if (data.hasOwnProperty('setting')) {
                obj['setting'] = ApiClient.convertToType(data['setting'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} app_id
 */
CheckSuitePreferencePreferencesAutoTriggerChecks.prototype['app_id'] = undefined;

/**
 * @member {Boolean} setting
 */
CheckSuitePreferencePreferencesAutoTriggerChecks.prototype['setting'] = undefined;






export default CheckSuitePreferencePreferencesAutoTriggerChecks;

