/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckRunOutput model module.
 * @module model/CheckRunOutput
 * @version 0.0.5
 */
class CheckRunOutput {
    /**
     * Constructs a new <code>CheckRunOutput</code>.
     * @alias module:model/CheckRunOutput
     * @param annotationsCount {Number} 
     * @param annotationsUrl {String} 
     * @param summary {String} 
     * @param text {String} 
     * @param title {String} 
     */
    constructor(annotationsCount, annotationsUrl, summary, text, title) { 
        
        CheckRunOutput.initialize(this, annotationsCount, annotationsUrl, summary, text, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, annotationsCount, annotationsUrl, summary, text, title) { 
        obj['annotations_count'] = annotationsCount;
        obj['annotations_url'] = annotationsUrl;
        obj['summary'] = summary;
        obj['text'] = text;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>CheckRunOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckRunOutput} obj Optional instance to populate.
     * @return {module:model/CheckRunOutput} The populated <code>CheckRunOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckRunOutput();

            if (data.hasOwnProperty('annotations_count')) {
                obj['annotations_count'] = ApiClient.convertToType(data['annotations_count'], 'Number');
            }
            if (data.hasOwnProperty('annotations_url')) {
                obj['annotations_url'] = ApiClient.convertToType(data['annotations_url'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} annotations_count
 */
CheckRunOutput.prototype['annotations_count'] = undefined;

/**
 * @member {String} annotations_url
 */
CheckRunOutput.prototype['annotations_url'] = undefined;

/**
 * @member {String} summary
 */
CheckRunOutput.prototype['summary'] = undefined;

/**
 * @member {String} text
 */
CheckRunOutput.prototype['text'] = undefined;

/**
 * @member {String} title
 */
CheckRunOutput.prototype['title'] = undefined;






export default CheckRunOutput;

