/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Traffic from './Traffic';

/**
 * The CloneTraffic model module.
 * @module model/CloneTraffic
 * @version 0.0.5
 */
class CloneTraffic {
    /**
     * Constructs a new <code>CloneTraffic</code>.
     * Clone Traffic
     * @alias module:model/CloneTraffic
     * @param clones {Array.<module:model/Traffic>} 
     * @param count {Number} 
     * @param uniques {Number} 
     */
    constructor(clones, count, uniques) { 
        
        CloneTraffic.initialize(this, clones, count, uniques);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, clones, count, uniques) { 
        obj['clones'] = clones;
        obj['count'] = count;
        obj['uniques'] = uniques;
    }

    /**
     * Constructs a <code>CloneTraffic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloneTraffic} obj Optional instance to populate.
     * @return {module:model/CloneTraffic} The populated <code>CloneTraffic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloneTraffic();

            if (data.hasOwnProperty('clones')) {
                obj['clones'] = ApiClient.convertToType(data['clones'], [Traffic]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('uniques')) {
                obj['uniques'] = ApiClient.convertToType(data['uniques'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Traffic>} clones
 */
CloneTraffic.prototype['clones'] = undefined;

/**
 * @member {Number} count
 */
CloneTraffic.prototype['count'] = undefined;

/**
 * @member {Number} uniques
 */
CloneTraffic.prototype['uniques'] = undefined;






export default CloneTraffic;

