/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CodeOfConduct model module.
 * @module model/CodeOfConduct
 * @version 0.0.5
 */
class CodeOfConduct {
    /**
     * Constructs a new <code>CodeOfConduct</code>.
     * Code Of Conduct
     * @alias module:model/CodeOfConduct
     * @param htmlUrl {String} 
     * @param key {String} 
     * @param name {String} 
     * @param url {String} 
     */
    constructor(htmlUrl, key, name, url) { 
        
        CodeOfConduct.initialize(this, htmlUrl, key, name, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, htmlUrl, key, name, url) { 
        obj['html_url'] = htmlUrl;
        obj['key'] = key;
        obj['name'] = name;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>CodeOfConduct</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CodeOfConduct} obj Optional instance to populate.
     * @return {module:model/CodeOfConduct} The populated <code>CodeOfConduct</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CodeOfConduct();

            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} body
 */
CodeOfConduct.prototype['body'] = undefined;

/**
 * @member {String} html_url
 */
CodeOfConduct.prototype['html_url'] = undefined;

/**
 * @member {String} key
 */
CodeOfConduct.prototype['key'] = undefined;

/**
 * @member {String} name
 */
CodeOfConduct.prototype['name'] = undefined;

/**
 * @member {String} url
 */
CodeOfConduct.prototype['url'] = undefined;






export default CodeOfConduct;

