/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CommitSearchResultItemParents model module.
 * @module model/CommitSearchResultItemParents
 * @version 0.0.5
 */
class CommitSearchResultItemParents {
    /**
     * Constructs a new <code>CommitSearchResultItemParents</code>.
     * @alias module:model/CommitSearchResultItemParents
     */
    constructor() { 
        
        CommitSearchResultItemParents.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CommitSearchResultItemParents</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CommitSearchResultItemParents} obj Optional instance to populate.
     * @return {module:model/CommitSearchResultItemParents} The populated <code>CommitSearchResultItemParents</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommitSearchResultItemParents();

            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} html_url
 */
CommitSearchResultItemParents.prototype['html_url'] = undefined;

/**
 * @member {String} sha
 */
CommitSearchResultItemParents.prototype['sha'] = undefined;

/**
 * @member {String} url
 */
CommitSearchResultItemParents.prototype['url'] = undefined;






export default CommitSearchResultItemParents;

