/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContributorActivityWeeks model module.
 * @module model/ContributorActivityWeeks
 * @version 0.0.5
 */
class ContributorActivityWeeks {
    /**
     * Constructs a new <code>ContributorActivityWeeks</code>.
     * @alias module:model/ContributorActivityWeeks
     */
    constructor() { 
        
        ContributorActivityWeeks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContributorActivityWeeks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContributorActivityWeeks} obj Optional instance to populate.
     * @return {module:model/ContributorActivityWeeks} The populated <code>ContributorActivityWeeks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContributorActivityWeeks();

            if (data.hasOwnProperty('a')) {
                obj['a'] = ApiClient.convertToType(data['a'], 'Number');
            }
            if (data.hasOwnProperty('c')) {
                obj['c'] = ApiClient.convertToType(data['c'], 'Number');
            }
            if (data.hasOwnProperty('d')) {
                obj['d'] = ApiClient.convertToType(data['d'], 'Number');
            }
            if (data.hasOwnProperty('w')) {
                obj['w'] = ApiClient.convertToType(data['w'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} a
 */
ContributorActivityWeeks.prototype['a'] = undefined;

/**
 * @member {Number} c
 */
ContributorActivityWeeks.prototype['c'] = undefined;

/**
 * @member {Number} d
 */
ContributorActivityWeeks.prototype['d'] = undefined;

/**
 * @member {String} w
 */
ContributorActivityWeeks.prototype['w'] = undefined;






export default ContributorActivityWeeks;

