/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GistsFiles model module.
 * @module model/GistsFiles
 * @version 0.0.5
 */
class GistsFiles {
    /**
     * Constructs a new <code>GistsFiles</code>.
     * @alias module:model/GistsFiles
     * @param content {String} Content of the file
     */
    constructor(content) { 
        
        GistsFiles.initialize(this, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content) { 
        obj['content'] = content;
    }

    /**
     * Constructs a <code>GistsFiles</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GistsFiles} obj Optional instance to populate.
     * @return {module:model/GistsFiles} The populated <code>GistsFiles</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GistsFiles();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Content of the file
 * @member {String} content
 */
GistsFiles.prototype['content'] = undefined;






export default GistsFiles;

