/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommitStats from './CommitStats';
import GistFullAllOfUser from './GistFullAllOfUser';

/**
 * The GistFullAllOfHistory model module.
 * @module model/GistFullAllOfHistory
 * @version 0.0.5
 */
class GistFullAllOfHistory {
    /**
     * Constructs a new <code>GistFullAllOfHistory</code>.
     * @alias module:model/GistFullAllOfHistory
     */
    constructor() { 
        
        GistFullAllOfHistory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GistFullAllOfHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GistFullAllOfHistory} obj Optional instance to populate.
     * @return {module:model/GistFullAllOfHistory} The populated <code>GistFullAllOfHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GistFullAllOfHistory();

            if (data.hasOwnProperty('change_status')) {
                obj['change_status'] = CommitStats.constructFromObject(data['change_status']);
            }
            if (data.hasOwnProperty('committed_at')) {
                obj['committed_at'] = ApiClient.convertToType(data['committed_at'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = GistFullAllOfUser.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CommitStats} change_status
 */
GistFullAllOfHistory.prototype['change_status'] = undefined;

/**
 * @member {String} committed_at
 */
GistFullAllOfHistory.prototype['committed_at'] = undefined;

/**
 * @member {String} url
 */
GistFullAllOfHistory.prototype['url'] = undefined;

/**
 * @member {module:model/GistFullAllOfUser} user
 */
GistFullAllOfHistory.prototype['user'] = undefined;

/**
 * @member {String} version
 */
GistFullAllOfHistory.prototype['version'] = undefined;






export default GistFullAllOfHistory;

