/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GitignoreTemplate model module.
 * @module model/GitignoreTemplate
 * @version 0.0.5
 */
class GitignoreTemplate {
    /**
     * Constructs a new <code>GitignoreTemplate</code>.
     * Gitignore Template
     * @alias module:model/GitignoreTemplate
     * @param name {String} 
     * @param source {String} 
     */
    constructor(name, source) { 
        
        GitignoreTemplate.initialize(this, name, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, source) { 
        obj['name'] = name;
        obj['source'] = source;
    }

    /**
     * Constructs a <code>GitignoreTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GitignoreTemplate} obj Optional instance to populate.
     * @return {module:model/GitignoreTemplate} The populated <code>GitignoreTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GitignoreTemplate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
GitignoreTemplate.prototype['name'] = undefined;

/**
 * @member {String} source
 */
GitignoreTemplate.prototype['source'] = undefined;






export default GitignoreTemplate;

