/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GitRefObject from './GitRefObject';

/**
 * The GitRef model module.
 * @module model/GitRef
 * @version 0.0.5
 */
class GitRef {
    /**
     * Constructs a new <code>GitRef</code>.
     * Git references within a repository
     * @alias module:model/GitRef
     */
    constructor() { 
        
        GitRef.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GitRef</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GitRef} obj Optional instance to populate.
     * @return {module:model/GitRef} The populated <code>GitRef</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GitRef();

            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = GitRefObject.constructFromObject(data['object']);
            }
            if (data.hasOwnProperty('ref')) {
                obj['ref'] = ApiClient.convertToType(data['ref'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} node_id
 */
GitRef.prototype['node_id'] = undefined;

/**
 * @member {module:model/GitRefObject} object
 */
GitRef.prototype['object'] = undefined;

/**
 * @member {String} ref
 */
GitRef.prototype['ref'] = undefined;

/**
 * @member {String} url
 */
GitRef.prototype['url'] = undefined;






export default GitRef;

