/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GitTagObject from './GitTagObject';
import GitTagTagger from './GitTagTagger';
import Verification from './Verification';

/**
 * The GitTag model module.
 * @module model/GitTag
 * @version 0.0.5
 */
class GitTag {
    /**
     * Constructs a new <code>GitTag</code>.
     * Metadata for a Git tag
     * @alias module:model/GitTag
     * @param message {String} Message describing the purpose of the tag
     * @param nodeId {String} 
     * @param _object {module:model/GitTagObject} 
     * @param sha {String} 
     * @param tag {String} Name of the tag
     * @param tagger {module:model/GitTagTagger} 
     * @param url {String} URL for the tag
     */
    constructor(message, nodeId, _object, sha, tag, tagger, url) { 
        
        GitTag.initialize(this, message, nodeId, _object, sha, tag, tagger, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, nodeId, _object, sha, tag, tagger, url) { 
        obj['message'] = message;
        obj['node_id'] = nodeId;
        obj['object'] = _object;
        obj['sha'] = sha;
        obj['tag'] = tag;
        obj['tagger'] = tagger;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>GitTag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GitTag} obj Optional instance to populate.
     * @return {module:model/GitTag} The populated <code>GitTag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GitTag();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = GitTagObject.constructFromObject(data['object']);
            }
            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('tagger')) {
                obj['tagger'] = GitTagTagger.constructFromObject(data['tagger']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('verification')) {
                obj['verification'] = Verification.constructFromObject(data['verification']);
            }
        }
        return obj;
    }


}

/**
 * Message describing the purpose of the tag
 * @member {String} message
 */
GitTag.prototype['message'] = undefined;

/**
 * @member {String} node_id
 */
GitTag.prototype['node_id'] = undefined;

/**
 * @member {module:model/GitTagObject} object
 */
GitTag.prototype['object'] = undefined;

/**
 * @member {String} sha
 */
GitTag.prototype['sha'] = undefined;

/**
 * Name of the tag
 * @member {String} tag
 */
GitTag.prototype['tag'] = undefined;

/**
 * @member {module:model/GitTagTagger} tagger
 */
GitTag.prototype['tagger'] = undefined;

/**
 * URL for the tag
 * @member {String} url
 */
GitTag.prototype['url'] = undefined;

/**
 * @member {module:model/Verification} verification
 */
GitTag.prototype['verification'] = undefined;






export default GitTag;

