/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GitTagObject model module.
 * @module model/GitTagObject
 * @version 0.0.5
 */
class GitTagObject {
    /**
     * Constructs a new <code>GitTagObject</code>.
     * @alias module:model/GitTagObject
     * @param sha {String} 
     * @param type {String} 
     * @param url {String} 
     */
    constructor(sha, type, url) { 
        
        GitTagObject.initialize(this, sha, type, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sha, type, url) { 
        obj['sha'] = sha;
        obj['type'] = type;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>GitTagObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GitTagObject} obj Optional instance to populate.
     * @return {module:model/GitTagObject} The populated <code>GitTagObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GitTagObject();

            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} sha
 */
GitTagObject.prototype['sha'] = undefined;

/**
 * @member {String} type
 */
GitTagObject.prototype['type'] = undefined;

/**
 * @member {String} url
 */
GitTagObject.prototype['url'] = undefined;






export default GitTagObject;

