/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HookConfig model module.
 * @module model/HookConfig
 * @version 0.0.5
 */
class HookConfig {
    /**
     * Constructs a new <code>HookConfig</code>.
     * @alias module:model/HookConfig
     */
    constructor() { 
        
        HookConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HookConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HookConfig} obj Optional instance to populate.
     * @return {module:model/HookConfig} The populated <code>HookConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HookConfig();

            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('digest')) {
                obj['digest'] = ApiClient.convertToType(data['digest'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('insecure_ssl')) {
                obj['insecure_ssl'] = ApiClient.convertToType(data['insecure_ssl'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('room')) {
                obj['room'] = ApiClient.convertToType(data['room'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('subdomain')) {
                obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} content_type
 */
HookConfig.prototype['content_type'] = undefined;

/**
 * @member {String} digest
 */
HookConfig.prototype['digest'] = undefined;

/**
 * @member {String} email
 */
HookConfig.prototype['email'] = undefined;

/**
 * @member {String} insecure_ssl
 */
HookConfig.prototype['insecure_ssl'] = undefined;

/**
 * @member {String} password
 */
HookConfig.prototype['password'] = undefined;

/**
 * @member {String} room
 */
HookConfig.prototype['room'] = undefined;

/**
 * @member {String} secret
 */
HookConfig.prototype['secret'] = undefined;

/**
 * @member {String} subdomain
 */
HookConfig.prototype['subdomain'] = undefined;

/**
 * @member {String} token
 */
HookConfig.prototype['token'] = undefined;

/**
 * @member {String} url
 */
HookConfig.prototype['url'] = undefined;






export default HookConfig;

