/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups from './OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups';

/**
 * The InlineObject38 model module.
 * @module model/InlineObject38
 * @version 0.0.5
 */
class InlineObject38 {
    /**
     * Constructs a new <code>InlineObject38</code>.
     * @alias module:model/InlineObject38
     * @param groups {Array.<module:model/OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups>} The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don't want to remove.
     */
    constructor(groups) { 
        
        InlineObject38.initialize(this, groups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groups) { 
        obj['groups'] = groups;
    }

    /**
     * Constructs a <code>InlineObject38</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject38} obj Optional instance to populate.
     * @return {module:model/InlineObject38} The populated <code>InlineObject38</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject38();

            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups]);
            }
        }
        return obj;
    }


}

/**
 * The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don't want to remove.
 * @member {Array.<module:model/OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups>} groups
 */
InlineObject38.prototype['groups'] = undefined;






export default InlineObject38;

