/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject141 model module.
 * @module model/InlineObject141
 * @version 0.0.5
 */
class InlineObject141 {
    /**
     * Constructs a new <code>InlineObject141</code>.
     * @alias module:model/InlineObject141
     * @param state {module:model/InlineObject141.StateEnum} The state that the membership should be in. Only `\"active\"` will be accepted.
     */
    constructor(state) { 
        
        InlineObject141.initialize(this, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state) { 
        obj['state'] = state;
    }

    /**
     * Constructs a <code>InlineObject141</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject141} obj Optional instance to populate.
     * @return {module:model/InlineObject141} The populated <code>InlineObject141</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject141();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The state that the membership should be in. Only `\"active\"` will be accepted.
 * @member {module:model/InlineObject141.StateEnum} state
 */
InlineObject141.prototype['state'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject141['StateEnum'] = {

    /**
     * value: "active"
     * @const
     */
    "active": "active"
};



export default InlineObject141;

