/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReposOwnerRepoContentsPathAuthor1 from './ReposOwnerRepoContentsPathAuthor1';
import ReposOwnerRepoContentsPathCommitter1 from './ReposOwnerRepoContentsPathCommitter1';

/**
 * The InlineObject61 model module.
 * @module model/InlineObject61
 * @version 0.0.5
 */
class InlineObject61 {
    /**
     * Constructs a new <code>InlineObject61</code>.
     * @alias module:model/InlineObject61
     * @param message {String} The commit message.
     * @param sha {String} The blob SHA of the file being replaced.
     */
    constructor(message, sha) { 
        
        InlineObject61.initialize(this, message, sha);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, sha) { 
        obj['message'] = message;
        obj['sha'] = sha;
    }

    /**
     * Constructs a <code>InlineObject61</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject61} obj Optional instance to populate.
     * @return {module:model/InlineObject61} The populated <code>InlineObject61</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject61();

            if (data.hasOwnProperty('author')) {
                obj['author'] = ReposOwnerRepoContentsPathAuthor1.constructFromObject(data['author']);
            }
            if (data.hasOwnProperty('branch')) {
                obj['branch'] = ApiClient.convertToType(data['branch'], 'String');
            }
            if (data.hasOwnProperty('committer')) {
                obj['committer'] = ReposOwnerRepoContentsPathCommitter1.constructFromObject(data['committer']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ReposOwnerRepoContentsPathAuthor1} author
 */
InlineObject61.prototype['author'] = undefined;

/**
 * The branch name. Default: the repository’s default branch (usually `master`)
 * @member {String} branch
 */
InlineObject61.prototype['branch'] = undefined;

/**
 * @member {module:model/ReposOwnerRepoContentsPathCommitter1} committer
 */
InlineObject61.prototype['committer'] = undefined;

/**
 * The commit message.
 * @member {String} message
 */
InlineObject61.prototype['message'] = undefined;

/**
 * The blob SHA of the file being replaced.
 * @member {String} sha
 */
InlineObject61.prototype['sha'] = undefined;






export default InlineObject61;

