/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject47 model module.
 * @module model/InlineObject47
 * @version 0.0.5
 */
class InlineObject47 {
    /**
     * Constructs a new <code>InlineObject47</code>.
     * @alias module:model/InlineObject47
     */
    constructor() { 
        
        InlineObject47.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject47</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject47} obj Optional instance to populate.
     * @return {module:model/InlineObject47} The populated <code>InlineObject47</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject47();

            if (data.hasOwnProperty('encrypted_value')) {
                obj['encrypted_value'] = ApiClient.convertToType(data['encrypted_value'], 'String');
            }
            if (data.hasOwnProperty('key_id')) {
                obj['key_id'] = ApiClient.convertToType(data['key_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Value for your secret, encrypted with [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages) using the public key retrieved from the [Get a repository public key](https://developer.github.com/v3/actions/secrets/#get-a-repository-public-key) endpoint.
 * @member {String} encrypted_value
 */
InlineObject47.prototype['encrypted_value'] = undefined;

/**
 * ID of the key you used to encrypt the secret.
 * @member {String} key_id
 */
InlineObject47.prototype['key_id'] = undefined;






export default InlineObject47;

