/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamsTeamIdTeamSyncGroupMappingsGroups from './TeamsTeamIdTeamSyncGroupMappingsGroups';

/**
 * The InlineObject136 model module.
 * @module model/InlineObject136
 * @version 0.0.5
 */
class InlineObject136 {
    /**
     * Constructs a new <code>InlineObject136</code>.
     * @alias module:model/InlineObject136
     * @param groups {Array.<module:model/TeamsTeamIdTeamSyncGroupMappingsGroups>} The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don't want to remove.
     */
    constructor(groups) { 
        
        InlineObject136.initialize(this, groups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groups) { 
        obj['groups'] = groups;
    }

    /**
     * Constructs a <code>InlineObject136</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject136} obj Optional instance to populate.
     * @return {module:model/InlineObject136} The populated <code>InlineObject136</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject136();

            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [TeamsTeamIdTeamSyncGroupMappingsGroups]);
            }
            if (data.hasOwnProperty('synced_at')) {
                obj['synced_at'] = ApiClient.convertToType(data['synced_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don't want to remove.
 * @member {Array.<module:model/TeamsTeamIdTeamSyncGroupMappingsGroups>} groups
 */
InlineObject136.prototype['groups'] = undefined;

/**
 * @member {String} synced_at
 */
InlineObject136.prototype['synced_at'] = undefined;






export default InlineObject136;

