/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject77 model module.
 * @module model/InlineObject77
 * @version 0.0.5
 */
class InlineObject77 {
    /**
     * Constructs a new <code>InlineObject77</code>.
     * @alias module:model/InlineObject77
     * @param useLfs {module:model/InlineObject77.UseLfsEnum} Can be one of `opt_in` (large files will be stored using Git LFS) or `opt_out` (large files will be removed during the import).
     */
    constructor(useLfs) { 
        
        InlineObject77.initialize(this, useLfs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, useLfs) { 
        obj['use_lfs'] = useLfs;
    }

    /**
     * Constructs a <code>InlineObject77</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject77} obj Optional instance to populate.
     * @return {module:model/InlineObject77} The populated <code>InlineObject77</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject77();

            if (data.hasOwnProperty('use_lfs')) {
                obj['use_lfs'] = ApiClient.convertToType(data['use_lfs'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Can be one of `opt_in` (large files will be stored using Git LFS) or `opt_out` (large files will be removed during the import).
 * @member {module:model/InlineObject77.UseLfsEnum} use_lfs
 */
InlineObject77.prototype['use_lfs'] = undefined;





/**
 * Allowed values for the <code>use_lfs</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject77['UseLfsEnum'] = {

    /**
     * value: "opt_in"
     * @const
     */
    "in": "opt_in",

    /**
     * value: "opt_out"
     * @const
     */
    "out": "opt_out"
};



export default InlineObject77;

