/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse403Block model module.
 * @module model/InlineResponse403Block
 * @version 0.0.5
 */
class InlineResponse403Block {
    /**
     * Constructs a new <code>InlineResponse403Block</code>.
     * @alias module:model/InlineResponse403Block
     */
    constructor() { 
        
        InlineResponse403Block.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse403Block</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse403Block} obj Optional instance to populate.
     * @return {module:model/InlineResponse403Block} The populated <code>InlineResponse403Block</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse403Block();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('html_url')) {
                obj['html_url'] = ApiClient.convertToType(data['html_url'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} created_at
 */
InlineResponse403Block.prototype['created_at'] = undefined;

/**
 * @member {String} html_url
 */
InlineResponse403Block.prototype['html_url'] = undefined;

/**
 * @member {String} reason
 */
InlineResponse403Block.prototype['reason'] = undefined;






export default InlineResponse403Block;

