/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject114 model module.
 * @module model/InlineObject114
 * @version 0.0.5
 */
class InlineObject114 {
    /**
     * Constructs a new <code>InlineObject114</code>.
     * @alias module:model/InlineObject114
     */
    constructor() { 
        
        InlineObject114.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject114</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject114} obj Optional instance to populate.
     * @return {module:model/InlineObject114} The populated <code>InlineObject114</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject114();

            if (data.hasOwnProperty('expected_head_sha')) {
                obj['expected_head_sha'] = ApiClient.convertToType(data['expected_head_sha'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The expected SHA of the pull request's HEAD ref. This is the most recent commit on the pull request's branch. If the expected SHA does not match the pull request's HEAD, you will receive a `422 Unprocessable Entity` status. You can use the \"[List commits](https://developer.github.com/v3/repos/commits/#list-commits)\" endpoint to find the most recent commit SHA. Default: SHA of the pull request's current HEAD ref.
 * @member {String} expected_head_sha
 */
InlineObject114.prototype['expected_head_sha'] = undefined;






export default InlineObject114;

