/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject69 model module.
 * @module model/InlineObject69
 * @version 0.0.5
 */
class InlineObject69 {
    /**
     * Constructs a new <code>InlineObject69</code>.
     * @alias module:model/InlineObject69
     * @param sha {String} The SHA1 value to set this reference to
     */
    constructor(sha) { 
        
        InlineObject69.initialize(this, sha);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sha) { 
        obj['sha'] = sha;
    }

    /**
     * Constructs a <code>InlineObject69</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject69} obj Optional instance to populate.
     * @return {module:model/InlineObject69} The populated <code>InlineObject69</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject69();

            if (data.hasOwnProperty('force')) {
                obj['force'] = ApiClient.convertToType(data['force'], 'Boolean');
            }
            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Indicates whether to force the update or to make sure the update is a fast-forward update. Leaving this out or setting it to `false` will make sure you're not overwriting work.
 * @member {Boolean} force
 * @default false
 */
InlineObject69.prototype['force'] = false;

/**
 * The SHA1 value to set this reference to
 * @member {String} sha
 */
InlineObject69.prototype['sha'] = undefined;






export default InlineObject69;

