/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject8 model module.
 * @module model/InlineObject8
 * @version 0.0.5
 */
class InlineObject8 {
    /**
     * Constructs a new <code>InlineObject8</code>.
     * @alias module:model/InlineObject8
     */
    constructor() { 
        
        InlineObject8.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject8</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject8} obj Optional instance to populate.
     * @return {module:model/InlineObject8} The populated <code>InlineObject8</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject8();

            if (data.hasOwnProperty('add_scopes')) {
                obj['add_scopes'] = ApiClient.convertToType(data['add_scopes'], ['String']);
            }
            if (data.hasOwnProperty('fingerprint')) {
                obj['fingerprint'] = ApiClient.convertToType(data['fingerprint'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('note_url')) {
                obj['note_url'] = ApiClient.convertToType(data['note_url'], 'String');
            }
            if (data.hasOwnProperty('remove_scopes')) {
                obj['remove_scopes'] = ApiClient.convertToType(data['remove_scopes'], ['String']);
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * A list of scopes to add to this authorization.
 * @member {Array.<String>} add_scopes
 */
InlineObject8.prototype['add_scopes'] = undefined;

/**
 * A unique string to distinguish an authorization from others created for the same client ID and user.
 * @member {String} fingerprint
 */
InlineObject8.prototype['fingerprint'] = undefined;

/**
 * A note to remind you what the OAuth token is for.
 * @member {String} note
 */
InlineObject8.prototype['note'] = undefined;

/**
 * A URL to remind you what app the OAuth token is for.
 * @member {String} note_url
 */
InlineObject8.prototype['note_url'] = undefined;

/**
 * A list of scopes to remove from this authorization.
 * @member {Array.<String>} remove_scopes
 */
InlineObject8.prototype['remove_scopes'] = undefined;

/**
 * A list of scopes that this authorization is in.
 * @member {Array.<String>} scopes
 */
InlineObject8.prototype['scopes'] = undefined;






export default InlineObject8;

