/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueEventRename model module.
 * @module model/IssueEventRename
 * @version 0.0.5
 */
class IssueEventRename {
    /**
     * Constructs a new <code>IssueEventRename</code>.
     * Issue Event Rename
     * @alias module:model/IssueEventRename
     * @param from {String} 
     * @param to {String} 
     */
    constructor(from, to) { 
        
        IssueEventRename.initialize(this, from, to);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, from, to) { 
        obj['from'] = from;
        obj['to'] = to;
    }

    /**
     * Constructs a <code>IssueEventRename</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueEventRename} obj Optional instance to populate.
     * @return {module:model/IssueEventRename} The populated <code>IssueEventRename</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueEventRename();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} from
 */
IssueEventRename.prototype['from'] = undefined;

/**
 * @member {String} to
 */
IssueEventRename.prototype['to'] = undefined;






export default IssueEventRename;

