/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueEventLabel model module.
 * @module model/IssueEventLabel
 * @version 0.0.5
 */
class IssueEventLabel {
    /**
     * Constructs a new <code>IssueEventLabel</code>.
     * Issue Event Label
     * @alias module:model/IssueEventLabel
     * @param color {String} 
     * @param name {String} 
     */
    constructor(color, name) { 
        
        IssueEventLabel.initialize(this, color, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, color, name) { 
        obj['color'] = color;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>IssueEventLabel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueEventLabel} obj Optional instance to populate.
     * @return {module:model/IssueEventLabel} The populated <code>IssueEventLabel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueEventLabel();

            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} color
 */
IssueEventLabel.prototype['color'] = undefined;

/**
 * @member {String} name
 */
IssueEventLabel.prototype['name'] = undefined;






export default IssueEventLabel;

