/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LabelSearchResultItem model module.
 * @module model/LabelSearchResultItem
 * @version 0.0.5
 */
class LabelSearchResultItem {
    /**
     * Constructs a new <code>LabelSearchResultItem</code>.
     * Label Search Result Item
     * @alias module:model/LabelSearchResultItem
     * @param color {String} 
     * @param _default {Boolean} 
     * @param description {String} 
     * @param id {Number} 
     * @param name {String} 
     * @param nodeId {String} 
     * @param score {Number} 
     * @param url {String} 
     */
    constructor(color, _default, description, id, name, nodeId, score, url) { 
        
        LabelSearchResultItem.initialize(this, color, _default, description, id, name, nodeId, score, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, color, _default, description, id, name, nodeId, score, url) { 
        obj['color'] = color;
        obj['default'] = _default;
        obj['description'] = description;
        obj['id'] = id;
        obj['name'] = name;
        obj['node_id'] = nodeId;
        obj['score'] = score;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>LabelSearchResultItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LabelSearchResultItem} obj Optional instance to populate.
     * @return {module:model/LabelSearchResultItem} The populated <code>LabelSearchResultItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LabelSearchResultItem();

            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('text_matches')) {
                obj['text_matches'] = ApiClient.convertToType(data['text_matches'], [Object]);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} color
 */
LabelSearchResultItem.prototype['color'] = undefined;

/**
 * @member {Boolean} default
 */
LabelSearchResultItem.prototype['default'] = undefined;

/**
 * @member {String} description
 */
LabelSearchResultItem.prototype['description'] = undefined;

/**
 * @member {Number} id
 */
LabelSearchResultItem.prototype['id'] = undefined;

/**
 * @member {String} name
 */
LabelSearchResultItem.prototype['name'] = undefined;

/**
 * @member {String} node_id
 */
LabelSearchResultItem.prototype['node_id'] = undefined;

/**
 * @member {Number} score
 */
LabelSearchResultItem.prototype['score'] = undefined;

/**
 * @member {Array.<Object>} text_matches
 */
LabelSearchResultItem.prototype['text_matches'] = undefined;

/**
 * @member {String} url
 */
LabelSearchResultItem.prototype['url'] = undefined;






export default LabelSearchResultItem;

