/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MarketplaceAccount model module.
 * @module model/MarketplaceAccount
 * @version 0.0.5
 */
class MarketplaceAccount {
    /**
     * Constructs a new <code>MarketplaceAccount</code>.
     * @alias module:model/MarketplaceAccount
     * @param id {Number} 
     * @param login {String} 
     * @param type {String} 
     * @param url {String} 
     */
    constructor(id, login, type, url) { 
        
        MarketplaceAccount.initialize(this, id, login, type, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, login, type, url) { 
        obj['id'] = id;
        obj['login'] = login;
        obj['type'] = type;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>MarketplaceAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MarketplaceAccount} obj Optional instance to populate.
     * @return {module:model/MarketplaceAccount} The populated <code>MarketplaceAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarketplaceAccount();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('organization_billing_email')) {
                obj['organization_billing_email'] = ApiClient.convertToType(data['organization_billing_email'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
MarketplaceAccount.prototype['email'] = undefined;

/**
 * @member {Number} id
 */
MarketplaceAccount.prototype['id'] = undefined;

/**
 * @member {String} login
 */
MarketplaceAccount.prototype['login'] = undefined;

/**
 * @member {String} node_id
 */
MarketplaceAccount.prototype['node_id'] = undefined;

/**
 * @member {String} organization_billing_email
 */
MarketplaceAccount.prototype['organization_billing_email'] = undefined;

/**
 * @member {String} type
 */
MarketplaceAccount.prototype['type'] = undefined;

/**
 * @member {String} url
 */
MarketplaceAccount.prototype['url'] = undefined;






export default MarketplaceAccount;

