/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrganizationSimple model module.
 * @module model/OrganizationSimple
 * @version 0.0.5
 */
class OrganizationSimple {
    /**
     * Constructs a new <code>OrganizationSimple</code>.
     * Organization Simple
     * @alias module:model/OrganizationSimple
     * @param avatarUrl {String} 
     * @param description {String} 
     * @param eventsUrl {String} 
     * @param hooksUrl {String} 
     * @param id {Number} 
     * @param issuesUrl {String} 
     * @param login {String} 
     * @param membersUrl {String} 
     * @param nodeId {String} 
     * @param publicMembersUrl {String} 
     * @param reposUrl {String} 
     * @param url {String} 
     */
    constructor(avatarUrl, description, eventsUrl, hooksUrl, id, issuesUrl, login, membersUrl, nodeId, publicMembersUrl, reposUrl, url) { 
        
        OrganizationSimple.initialize(this, avatarUrl, description, eventsUrl, hooksUrl, id, issuesUrl, login, membersUrl, nodeId, publicMembersUrl, reposUrl, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, avatarUrl, description, eventsUrl, hooksUrl, id, issuesUrl, login, membersUrl, nodeId, publicMembersUrl, reposUrl, url) { 
        obj['avatar_url'] = avatarUrl;
        obj['description'] = description;
        obj['events_url'] = eventsUrl;
        obj['hooks_url'] = hooksUrl;
        obj['id'] = id;
        obj['issues_url'] = issuesUrl;
        obj['login'] = login;
        obj['members_url'] = membersUrl;
        obj['node_id'] = nodeId;
        obj['public_members_url'] = publicMembersUrl;
        obj['repos_url'] = reposUrl;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>OrganizationSimple</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationSimple} obj Optional instance to populate.
     * @return {module:model/OrganizationSimple} The populated <code>OrganizationSimple</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationSimple();

            if (data.hasOwnProperty('avatar_url')) {
                obj['avatar_url'] = ApiClient.convertToType(data['avatar_url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('events_url')) {
                obj['events_url'] = ApiClient.convertToType(data['events_url'], 'String');
            }
            if (data.hasOwnProperty('hooks_url')) {
                obj['hooks_url'] = ApiClient.convertToType(data['hooks_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('issues_url')) {
                obj['issues_url'] = ApiClient.convertToType(data['issues_url'], 'String');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('members_url')) {
                obj['members_url'] = ApiClient.convertToType(data['members_url'], 'String');
            }
            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('public_members_url')) {
                obj['public_members_url'] = ApiClient.convertToType(data['public_members_url'], 'String');
            }
            if (data.hasOwnProperty('repos_url')) {
                obj['repos_url'] = ApiClient.convertToType(data['repos_url'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} avatar_url
 */
OrganizationSimple.prototype['avatar_url'] = undefined;

/**
 * @member {String} description
 */
OrganizationSimple.prototype['description'] = undefined;

/**
 * @member {String} events_url
 */
OrganizationSimple.prototype['events_url'] = undefined;

/**
 * @member {String} hooks_url
 */
OrganizationSimple.prototype['hooks_url'] = undefined;

/**
 * @member {Number} id
 */
OrganizationSimple.prototype['id'] = undefined;

/**
 * @member {String} issues_url
 */
OrganizationSimple.prototype['issues_url'] = undefined;

/**
 * @member {String} login
 */
OrganizationSimple.prototype['login'] = undefined;

/**
 * @member {String} members_url
 */
OrganizationSimple.prototype['members_url'] = undefined;

/**
 * @member {String} node_id
 */
OrganizationSimple.prototype['node_id'] = undefined;

/**
 * @member {String} public_members_url
 */
OrganizationSimple.prototype['public_members_url'] = undefined;

/**
 * @member {String} repos_url
 */
OrganizationSimple.prototype['repos_url'] = undefined;

/**
 * @member {String} url
 */
OrganizationSimple.prototype['url'] = undefined;






export default OrganizationSimple;

