/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PagesSourceHash model module.
 * @module model/PagesSourceHash
 * @version 0.0.5
 */
class PagesSourceHash {
    /**
     * Constructs a new <code>PagesSourceHash</code>.
     * @alias module:model/PagesSourceHash
     * @param branch {String} 
     * @param path {String} 
     */
    constructor(branch, path) { 
        
        PagesSourceHash.initialize(this, branch, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, branch, path) { 
        obj['branch'] = branch;
        obj['path'] = path;
    }

    /**
     * Constructs a <code>PagesSourceHash</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagesSourceHash} obj Optional instance to populate.
     * @return {module:model/PagesSourceHash} The populated <code>PagesSourceHash</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagesSourceHash();

            if (data.hasOwnProperty('branch')) {
                obj['branch'] = ApiClient.convertToType(data['branch'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} branch
 */
PagesSourceHash.prototype['branch'] = undefined;

/**
 * @member {String} path
 */
PagesSourceHash.prototype['path'] = undefined;






export default PagesSourceHash;

