/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BranchRestrictionPolicy from './BranchRestrictionPolicy';
import ProtectedBranchAllowDeletions from './ProtectedBranchAllowDeletions';
import ProtectedBranchEnforceAdmins from './ProtectedBranchEnforceAdmins';
import ProtectedBranchRequiredPullRequestReviews from './ProtectedBranchRequiredPullRequestReviews';
import ProtectedBranchRequiredSignatures from './ProtectedBranchRequiredSignatures';
import StatusCheckPolicy from './StatusCheckPolicy';

/**
 * The ProtectedBranch model module.
 * @module model/ProtectedBranch
 * @version 0.0.5
 */
class ProtectedBranch {
    /**
     * Constructs a new <code>ProtectedBranch</code>.
     * Branch protections protect branches
     * @alias module:model/ProtectedBranch
     * @param url {String} 
     */
    constructor(url) { 
        
        ProtectedBranch.initialize(this, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url) { 
        obj['url'] = url;
    }

    /**
     * Constructs a <code>ProtectedBranch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProtectedBranch} obj Optional instance to populate.
     * @return {module:model/ProtectedBranch} The populated <code>ProtectedBranch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProtectedBranch();

            if (data.hasOwnProperty('allow_deletions')) {
                obj['allow_deletions'] = ProtectedBranchAllowDeletions.constructFromObject(data['allow_deletions']);
            }
            if (data.hasOwnProperty('allow_force_pushes')) {
                obj['allow_force_pushes'] = ProtectedBranchAllowDeletions.constructFromObject(data['allow_force_pushes']);
            }
            if (data.hasOwnProperty('enforce_admins')) {
                obj['enforce_admins'] = ProtectedBranchEnforceAdmins.constructFromObject(data['enforce_admins']);
            }
            if (data.hasOwnProperty('required_linear_history')) {
                obj['required_linear_history'] = ProtectedBranchAllowDeletions.constructFromObject(data['required_linear_history']);
            }
            if (data.hasOwnProperty('required_pull_request_reviews')) {
                obj['required_pull_request_reviews'] = ProtectedBranchRequiredPullRequestReviews.constructFromObject(data['required_pull_request_reviews']);
            }
            if (data.hasOwnProperty('required_signatures')) {
                obj['required_signatures'] = ProtectedBranchRequiredSignatures.constructFromObject(data['required_signatures']);
            }
            if (data.hasOwnProperty('required_status_checks')) {
                obj['required_status_checks'] = StatusCheckPolicy.constructFromObject(data['required_status_checks']);
            }
            if (data.hasOwnProperty('restrictions')) {
                obj['restrictions'] = BranchRestrictionPolicy.constructFromObject(data['restrictions']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ProtectedBranchAllowDeletions} allow_deletions
 */
ProtectedBranch.prototype['allow_deletions'] = undefined;

/**
 * @member {module:model/ProtectedBranchAllowDeletions} allow_force_pushes
 */
ProtectedBranch.prototype['allow_force_pushes'] = undefined;

/**
 * @member {module:model/ProtectedBranchEnforceAdmins} enforce_admins
 */
ProtectedBranch.prototype['enforce_admins'] = undefined;

/**
 * @member {module:model/ProtectedBranchAllowDeletions} required_linear_history
 */
ProtectedBranch.prototype['required_linear_history'] = undefined;

/**
 * @member {module:model/ProtectedBranchRequiredPullRequestReviews} required_pull_request_reviews
 */
ProtectedBranch.prototype['required_pull_request_reviews'] = undefined;

/**
 * @member {module:model/ProtectedBranchRequiredSignatures} required_signatures
 */
ProtectedBranch.prototype['required_signatures'] = undefined;

/**
 * @member {module:model/StatusCheckPolicy} required_status_checks
 */
ProtectedBranch.prototype['required_status_checks'] = undefined;

/**
 * @member {module:model/BranchRestrictionPolicy} restrictions
 */
ProtectedBranch.prototype['restrictions'] = undefined;

/**
 * @member {String} url
 */
ProtectedBranch.prototype['url'] = undefined;






export default ProtectedBranch;

