/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReposOwnerRepoPullsPullNumberReviewsComments model module.
 * @module model/ReposOwnerRepoPullsPullNumberReviewsComments
 * @version 0.0.5
 */
class ReposOwnerRepoPullsPullNumberReviewsComments {
    /**
     * Constructs a new <code>ReposOwnerRepoPullsPullNumberReviewsComments</code>.
     * @alias module:model/ReposOwnerRepoPullsPullNumberReviewsComments
     * @param body {String} Text of the review comment.
     * @param path {String} The relative path to the file that necessitates a review comment.
     */
    constructor(body, path) { 
        
        ReposOwnerRepoPullsPullNumberReviewsComments.initialize(this, body, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, body, path) { 
        obj['body'] = body;
        obj['path'] = path;
    }

    /**
     * Constructs a <code>ReposOwnerRepoPullsPullNumberReviewsComments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReposOwnerRepoPullsPullNumberReviewsComments} obj Optional instance to populate.
     * @return {module:model/ReposOwnerRepoPullsPullNumberReviewsComments} The populated <code>ReposOwnerRepoPullsPullNumberReviewsComments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReposOwnerRepoPullsPullNumberReviewsComments();

            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('line')) {
                obj['line'] = ApiClient.convertToType(data['line'], 'Number');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('side')) {
                obj['side'] = ApiClient.convertToType(data['side'], 'String');
            }
            if (data.hasOwnProperty('start_line')) {
                obj['start_line'] = ApiClient.convertToType(data['start_line'], 'Number');
            }
            if (data.hasOwnProperty('start_side')) {
                obj['start_side'] = ApiClient.convertToType(data['start_side'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Text of the review comment.
 * @member {String} body
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['body'] = undefined;

/**
 * @member {Number} line
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['line'] = undefined;

/**
 * The relative path to the file that necessitates a review comment.
 * @member {String} path
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['path'] = undefined;

/**
 * The position in the diff where you want to add a review comment. Note this value is not the same as the line number in the file. For help finding the position value, read the note below.
 * @member {Number} position
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['position'] = undefined;

/**
 * @member {String} side
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['side'] = undefined;

/**
 * @member {Number} start_line
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['start_line'] = undefined;

/**
 * @member {String} start_side
 */
ReposOwnerRepoPullsPullNumberReviewsComments.prototype['start_side'] = undefined;






export default ReposOwnerRepoPullsPullNumberReviewsComments;

