/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RunnerApplication model module.
 * @module model/RunnerApplication
 * @version 0.0.5
 */
class RunnerApplication {
    /**
     * Constructs a new <code>RunnerApplication</code>.
     * Runner Application
     * @alias module:model/RunnerApplication
     */
    constructor() { 
        
        RunnerApplication.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RunnerApplication</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RunnerApplication} obj Optional instance to populate.
     * @return {module:model/RunnerApplication} The populated <code>RunnerApplication</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunnerApplication();

            if (data.hasOwnProperty('architecture')) {
                obj['architecture'] = ApiClient.convertToType(data['architecture'], 'String');
            }
            if (data.hasOwnProperty('download_url')) {
                obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('os')) {
                obj['os'] = ApiClient.convertToType(data['os'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} architecture
 */
RunnerApplication.prototype['architecture'] = undefined;

/**
 * @member {String} download_url
 */
RunnerApplication.prototype['download_url'] = undefined;

/**
 * @member {String} filename
 */
RunnerApplication.prototype['filename'] = undefined;

/**
 * @member {String} os
 */
RunnerApplication.prototype['os'] = undefined;






export default RunnerApplication;

