/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScimUserEmails model module.
 * @module model/ScimUserEmails
 * @version 0.0.5
 */
class ScimUserEmails {
    /**
     * Constructs a new <code>ScimUserEmails</code>.
     * @alias module:model/ScimUserEmails
     * @param value {String} 
     */
    constructor(value) { 
        
        ScimUserEmails.initialize(this, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value) { 
        obj['value'] = value;
    }

    /**
     * Constructs a <code>ScimUserEmails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScimUserEmails} obj Optional instance to populate.
     * @return {module:model/ScimUserEmails} The populated <code>ScimUserEmails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScimUserEmails();

            if (data.hasOwnProperty('primary')) {
                obj['primary'] = ApiClient.convertToType(data['primary'], 'Boolean');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} primary
 */
ScimUserEmails.prototype['primary'] = undefined;

/**
 * @member {String} value
 */
ScimUserEmails.prototype['value'] = undefined;






export default ScimUserEmails;

