/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitHubV3RestApi);
  }
}(this, function(expect, GitHubV3RestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitHubV3RestApi.CheckAnnotation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CheckAnnotation', function() {
    it('should create an instance of CheckAnnotation', function() {
      // uncomment below and update the code to test CheckAnnotation
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be.a(GitHubV3RestApi.CheckAnnotation);
    });

    it('should have the property annotationLevel (base name: "annotation_level")', function() {
      // uncomment below and update the code to test the property annotationLevel
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property blobHref (base name: "blob_href")', function() {
      // uncomment below and update the code to test the property blobHref
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property endColumn (base name: "end_column")', function() {
      // uncomment below and update the code to test the property endColumn
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property endLine (base name: "end_line")', function() {
      // uncomment below and update the code to test the property endLine
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property rawDetails (base name: "raw_details")', function() {
      // uncomment below and update the code to test the property rawDetails
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property startColumn (base name: "start_column")', function() {
      // uncomment below and update the code to test the property startColumn
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property startLine (base name: "start_line")', function() {
      // uncomment below and update the code to test the property startLine
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new GitHubV3RestApi.CheckAnnotation();
      //expect(instance).to.be();
    });

  });

}));
