/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitHubV3RestApi);
  }
}(this, function(expect, GitHubV3RestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitHubV3RestApi.ScopedInstallation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScopedInstallation', function() {
    it('should create an instance of ScopedInstallation', function() {
      // uncomment below and update the code to test ScopedInstallation
      //var instane = new GitHubV3RestApi.ScopedInstallation();
      //expect(instance).to.be.a(GitHubV3RestApi.ScopedInstallation);
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instane = new GitHubV3RestApi.ScopedInstallation();
      //expect(instance).to.be();
    });

    it('should have the property permissions (base name: "permissions")', function() {
      // uncomment below and update the code to test the property permissions
      //var instane = new GitHubV3RestApi.ScopedInstallation();
      //expect(instance).to.be();
    });

    it('should have the property repositoriesUrl (base name: "repositories_url")', function() {
      // uncomment below and update the code to test the property repositoriesUrl
      //var instane = new GitHubV3RestApi.ScopedInstallation();
      //expect(instance).to.be();
    });

    it('should have the property repositorySelection (base name: "repository_selection")', function() {
      // uncomment below and update the code to test the property repositorySelection
      //var instane = new GitHubV3RestApi.ScopedInstallation();
      //expect(instance).to.be();
    });

    it('should have the property singleFileName (base name: "single_file_name")', function() {
      // uncomment below and update the code to test the property singleFileName
      //var instane = new GitHubV3RestApi.ScopedInstallation();
      //expect(instance).to.be();
    });

  });

}));
