/**
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GitHubV3RestApi);
  }
}(this, function(expect, GitHubV3RestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GitHubV3RestApi.UserMarketplacePurchase();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserMarketplacePurchase', function() {
    it('should create an instance of UserMarketplacePurchase', function() {
      // uncomment below and update the code to test UserMarketplacePurchase
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be.a(GitHubV3RestApi.UserMarketplacePurchase);
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property billingCycle (base name: "billing_cycle")', function() {
      // uncomment below and update the code to test the property billingCycle
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property freeTrialEndsOn (base name: "free_trial_ends_on")', function() {
      // uncomment below and update the code to test the property freeTrialEndsOn
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property nextBillingDate (base name: "next_billing_date")', function() {
      // uncomment below and update the code to test the property nextBillingDate
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property onFreeTrial (base name: "on_free_trial")', function() {
      // uncomment below and update the code to test the property onFreeTrial
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property plan (base name: "plan")', function() {
      // uncomment below and update the code to test the property plan
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property unitCount (base name: "unit_count")', function() {
      // uncomment below and update the code to test the property unitCount
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new GitHubV3RestApi.UserMarketplacePurchase();
      //expect(instance).to.be();
    });

  });

}));
